// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Carrito", b =>
                {
                    b.Property<Guid>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("CarritoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("Domain.Entities.CarritoProducto", b =>
                {
                    b.Property<Guid>("CarritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("CarritoId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CarritoProducto");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido = "Yedro",
                            DNI = "43655405",
                            Direccion = "Calle 17 1234",
                            Nombre = "Valentin",
                            Telefono = "1125908161"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Orden", b =>
                {
                    b.Property<Guid>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("OrdenId");

                    b.HasIndex("CarritoId")
                        .IsUnique();

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Codigo = "#1",
                            Descripcion = "Un mate estilo camionero con virola de aluminio y recubierto de cuero.\r\n• Mate elaborado con calabaza brasilera seleccionada.\r\n• Virola de aluminio lisa.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.",
                            Image = "https://i.imgur.com/kBpL61h.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate camionero ALUMINIO",
                            Precio = 2000m
                        },
                        new
                        {
                            ProductoId = 2,
                            Codigo = "#2",
                            Descripcion = "Un mate estilo torpedo con virola de aluminio y recubierto de cuero.\r\n• Mate elaborado con calabaza brasilera seleccionada.\r\n• Virola de aluminio lisa.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.",
                            Image = "https://i.imgur.com/OBgi9Rq.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate torpedo ALUMINIO",
                            Precio = 2000m
                        },
                        new
                        {
                            ProductoId = 3,
                            Codigo = "#3",
                            Descripcion = "Un mate estilo camionero con virola de aluminio cincelada y recubierto de cuero.\r\n• Mate elaborado con calabaza brasilera seleccionada.\r\n• Virola de aluminio cincelada.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.\r\n• Los mejores detalles para un mate mucho más estético.",
                            Image = "https://i.imgur.com/rTMC88Q.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate camionero ALUMINIO CINCELADO",
                            Precio = 2300m
                        },
                        new
                        {
                            ProductoId = 4,
                            Codigo = "#4",
                            Descripcion = "Un mate estilo torpedo con virola de aluminio cincelada y recubierto de cuero.\r\n• Mate elaborado con calabaza brasilera seleccionada.\r\n• Virola de aluminio cincelada.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.\r\n• Los mejores detalles para un mate mucho más estético.",
                            Image = "https://i.imgur.com/lnaf51K.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate torpedo ALUMINIO CINCELADO",
                            Precio = 2300m
                        },
                        new
                        {
                            ProductoId = 5,
                            Codigo = "#5",
                            Descripcion = "Un mate estilo camionero con virola de alpaca lisa y recubierto de cuero.\r\n• La máxima calidad en la virola tu mate.\r\n• Elaborado con calabaza brasilera seleccionada para una calidad óptima.\r\n• Virola de alpaca lisa.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.",
                            Image = "https://i.imgur.com/QChC7FG.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate camionero ALPACA LISA",
                            Precio = 3000m
                        },
                        new
                        {
                            ProductoId = 6,
                            Codigo = "#6",
                            Descripcion = "Un mate estilo torpedo con virola de alpaca lisa y recubierto de cuero.\r\n• La máxima calidad en la virola tu mate.\r\n• Elaborado con calabaza brasilera seleccionada para una calidad óptima.\r\n• Virola de alpaca lisa.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.",
                            Image = "https://i.imgur.com/gRMsfCx.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate torpedo ALPACA LISA",
                            Precio = 3000m
                        },
                        new
                        {
                            ProductoId = 7,
                            Codigo = "#7",
                            Descripcion = "Un mate estilo camionero con virola de alpaca cincelada y recubierto de cuero.\r\n• La máxima calidad y detalle en la virola tu mate.\r\n• Elaborado con calabaza brasilera seleccionada para una calidad óptima.\r\n• Virola de alpaca cincelada.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.",
                            Image = "https://i.imgur.com/gt1RiK4.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate camionero ALPACA CINCELADA",
                            Precio = 3300m
                        },
                        new
                        {
                            ProductoId = 8,
                            Codigo = "#8",
                            Descripcion = "Un mate estilo torpedo con virola de alpaca cincelada y recubierto de cuero.\r\n• La máxima calidad y detalle en la virola tu mate.\r\n• Elaborado con calabaza brasilera seleccionada para una calidad óptima.\r\n• Virola de alpaca cincelada.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.",
                            Image = "https://i.imgur.com/DNDhDf6.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate torpedo ALPACA CINCELADA",
                            Precio = 3300m
                        },
                        new
                        {
                            ProductoId = 9,
                            Codigo = "#9",
                            Descripcion = "Un mate estilo camionero con virola de alpaca grabada totalmente personalizada y recubierto de cuero.\r\n• Elaborado con calabaza brasilera seleccionada para una calidad óptima.\r\n• Virola de alpaca.\r\n• Grabado láser.\r\n• Forrado en cuero.\r\n• Con refuerzo en las patas para máxima estabilidad.\r\n• ¡Pedinos tu diseño y te lo hacemos!",
                            Image = "https://i.imgur.com/Slb5Ojf.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Mate camionero ALPACA GRABADA",
                            Precio = 4200m
                        },
                        new
                        {
                            ProductoId = 10,
                            Codigo = "#10",
                            Descripcion = "Una bombilla ideal para un mate ideal. Con estilo pico loro para máximo confort.\r\n• Acero inoxidable.\r\n• Medida aproximada: 19cm.\r\n• Bombilla estilo pico loro para mayor confort.",
                            Image = "https://i.imgur.com/3UPfdzA.jpg",
                            Marca = "Mates Berazategui",
                            Nombre = "Bombilla pico loro ACERO INOXIDABLE",
                            Precio = 800m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Carrito", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("Carritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.CarritoProducto", b =>
                {
                    b.HasOne("Domain.Entities.Carrito", "Carrito")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Orden", b =>
                {
                    b.HasOne("Domain.Entities.Carrito", "Carrito")
                        .WithOne("Orden")
                        .HasForeignKey("Domain.Entities.Orden", "CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("Domain.Entities.Carrito", b =>
                {
                    b.Navigation("CarritoProductos");

                    b.Navigation("Orden")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Carritos");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("CarritoProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
